/* Generated by Cottontail bun:ffi.viewSource(). */
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
typedef void *napi_env;
typedef void *napi_value;
/* Dynamic-library symbol declaration used by libffi. */
float not_a_callback(float arg0);
