/* Generated by Cottontail bun:ffi.viewSource(). */
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>
typedef void *napi_env;
typedef void *napi_value;
/* Callback ABI declaration used by the libffi closure. */
bool my_callback_function(void * arg0);
