// Regenerates ./readable-stream.js from readable-stream@4.7.0.
//
// Usage (needs network access and npm on PATH):
//   cottontail readable-stream.build.mjs [outfile]
//
// Downloads readable-stream via `npm pack` into a temp dir, applies the
// Cottontail compat patches below, and bundles a single ESM file whose only
// imports are ../events.js, ../buffer.js and ../string_decoder.js.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execSync } from "node:child_process";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const SCRATCH = fs.mkdtempSync(path.join(os.tmpdir(), "readable-stream-build-"));

execSync("npm pack readable-stream@4.7.0", { cwd: SCRATCH, stdio: "inherit" });
execSync("tar xzf readable-stream-4.7.0.tgz", { cwd: SCRATCH, stdio: "inherit" });
const PKG = path.join(SCRATCH, "package");
const OUT = process.argv[2] ?? path.join(HERE, "readable-stream.js");

// Entry: readable-stream's full custom stream (Node core port) + promises.
const entrySource = `
import Stream from ${JSON.stringify(path.join(PKG, "lib/stream.js"))};
Stream._isArrayBufferView ??= ArrayBuffer.isView;
export default Stream;
`;

const shims = {
  "process/": `
    var p = globalThis.process;
    if (!p) {
      p = { env: {}, nextTick: function (cb) { var a = [].slice.call(arguments, 1); queueMicrotask(function () { cb.apply(null, a); }); } };
    }
    module.exports = p;
  `,
  "abort-controller": `
    // Lazy shims: the runtime installs globalThis.AbortController/AbortSignal
    // after this module is evaluated, so delegate at construction/access time.
    class AbortControllerShim {
      constructor() {
        return new globalThis.AbortController();
      }
    }
    const AbortSignalShim = {
      get any() {
        const ctor = globalThis.AbortSignal;
        return ctor && ctor.any ? ctor.any.bind(ctor) : undefined;
      },
      get abort() {
        const ctor = globalThis.AbortSignal;
        return ctor && ctor.abort ? ctor.abort.bind(ctor) : undefined;
      },
      get timeout() {
        const ctor = globalThis.AbortSignal;
        return ctor && ctor.timeout ? ctor.timeout.bind(ctor) : undefined;
      },
    };
    module.exports = { AbortController: AbortControllerShim, AbortSignal: AbortSignalShim };
  `,
  events: `
    // The runtime EventEmitter is a Node-style callable function constructor
    // (EE.call(this) works from readable-stream's function constructors), so
    // it can be re-exported directly.
    module.exports = {
      EventEmitter: __ct_EventEmitter,
      addAbortListener: __ct_addAbortListener,
      once: __ct_events_once,
      errorMonitor: __ct_errorMonitor,
    };
  `,
  buffer: `
    module.exports = { Buffer: __ct_Buffer, Blob: __ct_Blob };
  `,
  "string_decoder/": `
    module.exports = { StringDecoder: __ct_StringDecoder };
  `,
};

const banner = `// Vendored from readable-stream@4.7.0 (https://github.com/nodejs/readable-stream)
// A userland copy of the Node.js core streams implementation. License: MIT.
// Generated by readable-stream.build.mjs (same directory); do not edit by hand.
//
// Cottontail deltas from upstream readable-stream:
// - events/buffer/string_decoder resolve to the runtime modules (banner
//   imports below); the events shim re-exports the runtime EventEmitter,
//   which is a Node-style callable function constructor.
// - abort-controller/process shims resolve lazily to runtime globals.
// - primordials' ObjectDefineProperty(ies) force accessor descriptors to be
//   configurable so node/stream.js can install compat setters.
// - Readable constructor: legacy push-style sources (no _read, overridden
//   pause/resume) start in flowing mode with a no-op _read.
// - byte-mode readable/writable streams accept every ArrayBufferView.
// - Writable object-mode writes of non-string chunks report encoding
//   undefined (Bun behavior).
// - byte-mode streams use Node's current 64 KiB default high-water mark.
// - Readable/Writable validate defaultEncoding during construction.
// - Writable implements Symbol.asyncDispose.
// - stream constructors preallocate Node's common event slots.
// - successful Writable end callbacks receive null.
// - Duplex uses Writable's destroy path so buffered write callbacks settle.
// - destroy() honors an explicit public destroyed=true compatibility marker.
// - end-of-stream: a 'close' after EOF (state.ended) is not premature.
// - end-of-stream waits for queued writable callbacks and pending EOF events.
// - internally-started async work is rejection-observed immediately.
// - compose retains tail error forwarding through post-input async failures.
// - async iterator consults _readableState.destroyed (legacy modules shadow
//   stream.destroyed with an own property).
// - endReadableNT emits the EOF null-'readable' when a legacy eager source
//   pushed EOF while data was still buffered.
// - debuglog traces to console.error when globalThis.__ct_stream_debug.
import { EventEmitter as __ct_EventEmitter, addAbortListener as __ct_addAbortListener, once as __ct_events_once, errorMonitor as __ct_errorMonitor } from "../events.js";
import { Buffer as __ct_Buffer, Blob as __ct_Blob } from "../buffer.js";
import { StringDecoder as __ct_StringDecoder } from "../string_decoder.js";
`;

// Text patches applied to vendored sources (documented in bundle header).
const patches = [
  {
    // Current Node preallocates common event slots in this order. The shared
    // EventEmitter preserves the object and increments _eventsCount only when
    // a real listener replaces an undefined slot.
    file: /internal\/streams\/readable\.js$/,
    find: `function Readable(options) {
  if (!(this instanceof Readable)) return new Readable(options)`,
    replace: `function Readable(options) {
  if (!(this instanceof Readable)) return new Readable(options)
  if (this._events == null) {
    this._events = {
      __proto__: null,
      close: undefined,
      error: undefined,
      data: undefined,
      end: undefined,
      readable: undefined
    }
  }`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `function Writable(options) {
  // Writable ctor is applied to Duplexes, too.`,
    replace: `function Writable(options) {
  if (this._events == null) {
    this._events = {
      __proto__: null,
      close: undefined,
      error: undefined,
      prefinish: undefined,
      finish: undefined,
      drain: undefined
    }
  }
  // Writable ctor is applied to Duplexes, too.`,
  },
  {
    file: /internal\/streams\/duplex\.js$/,
    find: `function Duplex(options) {
  if (!(this instanceof Duplex)) return new Duplex(options)`,
    replace: `function Duplex(options) {
  if (!(this instanceof Duplex)) return new Duplex(options)
  if (this._events == null) {
    this._events = {
      __proto__: null,
      close: undefined,
      error: undefined,
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      data: undefined,
      end: undefined,
      readable: undefined
    }
  }`,
  },
  {
    // Current Node accepts all typed-array and DataView chunks, converting
    // them to Buffer in byte mode while preserving them in object mode.
    file: /internal\/streams\/(?:readable|writable)\.js$/,
    find: `Stream._isUint8Array(chunk)`,
    replace: `Stream._isArrayBufferView(chunk)`,
  },
  {
    // A destination async generator can throw after consuming its final input.
    // The pipeline may already have completed its source-side bookkeeping and
    // removed its listener, so compose must retain its own forwarding path.
    file: /internal\/streams\/compose\.js$/,
    find: `  d = new Duplex({
    // TODO (ronag): highWaterMark?
    writableObjectMode: !!(head !== null && head !== undefined && head.writableObjectMode),
    readableObjectMode: !!(tail !== null && tail !== undefined && tail.readableObjectMode),
    writable,
    readable
  })`,
    replace: `  d = new Duplex({
    // TODO (ronag): highWaterMark?
    writableObjectMode: !!(head !== null && head !== undefined && head.writableObjectMode),
    readableObjectMode: !!(tail !== null && tail !== undefined && tail.readableObjectMode),
    writable,
    readable
  })
  if (isNodeStream(tail)) {
    tail.on('error', (err) => d.destroy(err))
  }`,
  },
  {
    // Internal async iteration is intentionally fire-and-drive: stream events
    // carry its failure. Observe a defensive rejection from the driver
    // immediately so Cottontail does not classify it as top-level unhandled.
    file: /internal\/streams\/from\.js$/,
    find: `      reading = true
      next()`,
    replace: `      reading = true
      PromisePrototypeThen(next(), undefined, (err) => readable.destroy(err))`,
  },
  {
    // The promise returned by the user function can reject before _final gets
    // a chance to await it. This observer marks it handled without changing
    // the original promise consumed by _final.
    file: /internal\/streams\/duplexify\.js$/,
    find: `const { FunctionPrototypeCall } = require('../../ours/primordials')`,
    replace: `const { FunctionPrototypeCall, PromisePrototypeCatch } = require('../../ours/primordials')`,
  },
  {
    file: /internal\/streams\/duplexify\.js$/,
    find: `      )
      return (d = new Duplexify({`,
    replace: `      )
      PromisePrototypeCatch(promise, () => {})
      return (d = new Duplexify({`,
  },
  {
    // Duplex inherits Readable.destroy, but writable teardown must also fail
    // corked and buffered write callbacks. Current Node explicitly installs
    // Writable's destroy implementation after mixing in writable methods.
    file: /internal\/streams\/duplex\.js$/,
    find: `}
function Duplex(options) {`,
    replace: `}
Duplex.prototype.destroy = Writable.prototype.destroy
function Duplex(options) {`,
  },
  {
    // node/stream.js lets legacy modules shadow the destroyed accessor without
    // mutating stream state. Public destroy() must still honor that explicit
    // marker, as Node does for an assigned destroyed=true value.
    file: /internal\/streams\/destroy\.js$/,
    find: `  if ((w !== null && w !== undefined && w.destroyed) || (r !== null && r !== undefined && r.destroyed)) {`,
    replace: `  if (this.destroyed || (w !== null && w !== undefined && w.destroyed) || (r !== null && r !== undefined && r.destroyed)) {`,
  },
  {
    // Node changed the byte-stream default from 16 KiB to 64 KiB. Keep the
    // object-mode default at 16.
    file: /internal\/streams\/state\.js$/,
    find: `let defaultHighWaterMarkBytes = 16 * 1024`,
    replace: `let defaultHighWaterMarkBytes = 64 * 1024`,
  },
  {
    // Current Node rejects an invalid default encoding at construction time,
    // before the stream has accepted any chunks.
    file: /internal\/streams\/readable\.js$/,
    find: `    ERR_STREAM_PUSH_AFTER_EOF,
    ERR_STREAM_UNSHIFT_AFTER_END_EVENT`,
    replace: `    ERR_STREAM_PUSH_AFTER_EOF,
    ERR_STREAM_UNSHIFT_AFTER_END_EVENT,
    ERR_UNKNOWN_ENCODING`,
  },
  {
    file: /internal\/streams\/readable\.js$/,
    find: `  this.defaultEncoding = (options && options.defaultEncoding) || 'utf8'`,
    replace: `  this.defaultEncoding = (options && options.defaultEncoding) || 'utf8'
  if (!Buffer.isEncoding(this.defaultEncoding)) throw new ERR_UNKNOWN_ENCODING(String(this.defaultEncoding))`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `  this.defaultEncoding = (options && options.defaultEncoding) || 'utf8'`,
    replace: `  this.defaultEncoding = (options && options.defaultEncoding) || 'utf8'
  if (!Buffer.isEncoding(this.defaultEncoding)) throw new ERR_UNKNOWN_ENCODING(String(this.defaultEncoding))`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `      errorOrDestroy(stream, err !== null && err !== undefined ? err : ERR_MULTIPLE_CALLBACK())`,
    replace: `      errorOrDestroy(stream, err !== null && err !== undefined ? err : new ERR_MULTIPLE_CALLBACK())`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `  if (!Buffer.isEncoding(encoding)) throw new ERR_UNKNOWN_ENCODING(encoding)
  this._writableState.defaultEncoding = encoding`,
    replace: `  if (!Buffer.isEncoding(encoding)) throw new ERR_UNKNOWN_ENCODING(String(encoding))
  this._writableState.defaultEncoding = encoding`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `  for (let i = 0; i < onfinishCallbacks.length; i++) {
    onfinishCallbacks[i]()
  }`,
    replace: `  for (let i = 0; i < onfinishCallbacks.length; i++) {
    onfinishCallbacks[i](null)
  }`,
  },
  {
    // readable-stream@4.7 predates Writable's async-dispose implementation.
    file: /internal\/streams\/writable\.js$/,
    find: `  ObjectSetPrototypeOf,
  StringPrototypeToLowerCase,
  Symbol,
  SymbolHasInstance`,
    replace: `  ObjectSetPrototypeOf,
  Promise,
  StringPrototypeToLowerCase,
  Symbol,
  SymbolAsyncDispose,
  SymbolHasInstance`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `const {
  ERR_INVALID_ARG_TYPE,`,
    replace: `const { AbortError } = require('../../ours/errors')
const {
  ERR_INVALID_ARG_TYPE,`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `const { addAbortSignal } = require('./add-abort-signal')`,
    replace: `const { addAbortSignal } = require('./add-abort-signal')
const eos = require('./end-of-stream')`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `Writable.prototype[EE.captureRejectionSymbol] = function (err) {
  this.destroy(err)
}`,
    replace: `Writable.prototype[EE.captureRejectionSymbol] = function (err) {
  this.destroy(err)
}
Writable.prototype[SymbolAsyncDispose] = function () {
  let error
  if (!this.destroyed) {
    error = this.writableFinished ? null : new AbortError()
    this.destroy(error)
  }
  return new Promise((resolve, reject) =>
    eos(this, (err) => (err && err.name !== 'AbortError' ? reject(err) : resolve(null)))
  )
}`,
  },
  {
    // Make prototype accessor properties configurable so node/stream.js can
    // install permissive setters for legacy runtime-module subclasses.
    file: /ours\/primordials\.js$/,
    find: `  ObjectDefineProperties(self, props) {
    return Object.defineProperties(self, props)
  },
  ObjectDefineProperty(self, name, prop) {
    return Object.defineProperty(self, name, prop)
  },`,
    replace: `  ObjectDefineProperties(self, props) {
    for (const key of Object.keys(props)) {
      const prop = props[key]
      if (prop && (prop.get || prop.set) && !('configurable' in prop)) prop.configurable = true
    }
    return Object.defineProperties(self, props)
  },
  ObjectDefineProperty(self, name, prop) {
    if (prop && (prop.get || prop.set) && !('configurable' in prop)) {
      prop = { ...prop, configurable: true }
    }
    return Object.defineProperty(self, name, prop)
  },`,
  },
  {
    // Cottontail compat: several runtime modules (fs.ReadStream, net.Socket,
    // child_process stdio) are legacy push-style sources: they push() data
    // themselves, never implement _read, and override pause()/resume() with
    // versions that do not drive the real flow-control state machine. Start
    // such streams in flowing mode so buffered chunks are delivered.
    file: /internal\/streams\/readable\.js$/,
    find: `  Stream.call(this, options)
  destroyImpl.construct(this, () => {`,
    replace: `  Stream.call(this, options)
  if (
    this._read === Readable.prototype._read &&
    (this.resume !== Readable.prototype.resume || this.pause !== Readable.prototype.pause)
  ) {
    this._readableState.ctLegacyEager = true
    this._readableState.flowing = true
    this._read = function () {}
  }
  destroyImpl.construct(this, () => {`,
  },
  {
    // Cottontail compat: legacy sources (fs.ReadStream, ...) emit 'close'
    // manually right after push(null), before 'end' has been delivered.
    // Once EOF has been signalled (state.ended), a close is not premature.
    // fs.ReadStream also exposes readableEnded before its buffered final chunk
    // has drained, whereas the standard Readable getter waits for 'end'.
    file: /internal\/streams\/end-of-stream\.js$/,
    find: `    if (readable && !readableFinished && isReadableNodeStream(stream, true)) {
      if (!isReadableFinished(stream, false)) return callback.call(stream, new ERR_STREAM_PREMATURE_CLOSE())
    }`,
    replace: `    if (readable && !readableFinished && isReadableNodeStream(stream, true)) {
      const rEndedState = stream._readableState
      // Legacy Cottontail sources can emit close immediately after push(null).
      // EOF is queued, but the already-registered end listener must complete
      // eos so callers observe all preceding end listeners first.
      if (
        rEndedState &&
        rEndedState.ended === true &&
        rEndedState.endEmitted !== true &&
        rEndedState.destroyed !== true &&
        (rEndedState.length === 0 || stream.readableEnded === true)
      ) return
      if (!isReadableFinished(stream, false)) {
        return callback.call(stream, new ERR_STREAM_PREMATURE_CLOSE())
      }
    }`,
  },
  {
    // Cottontail compat: legacy sources assign \`stream.destroyed = true\`
    // (shadowed as an own property by node/stream.js) while buffered data is
    // still pending; consult the real state so iteration drains the buffer.
    file: /internal\/streams\/readable\.js$/,
    find: `      const chunk = stream.destroyed ? null : stream.read()`,
    replace: `      const chunk = (stream._readableState ? stream._readableState.destroyed : stream.destroyed)
        ? null
        : stream.read()`,
  },
  {
    file: /internal\/streams\/writable\.js$/,
    find: `      throw new ERR_INVALID_ARG_TYPE('chunk', ['string', 'Buffer', 'Uint8Array'], chunk)
    }
  }`,
    replace: `      throw new ERR_INVALID_ARG_TYPE('chunk', ['string', 'Buffer', 'Uint8Array'], chunk)
    }
  } else if (typeof chunk !== 'string' && encoding === state.defaultEncoding) {
    // Bun/Cottontail: object-mode writes of non-string chunks report an
    // undefined encoding (matches Bun's native streams).
    encoding = undefined
  }`,
  },
];

patches.push({
  // Ending a writable makes isWritable() false before its queued callbacks
  // have run. Do not report completion until those callbacks are drained.
  file: /internal\/streams\/end-of-stream\.js$/,
  find: `    (writableFinished || isWritable(stream) === false)
  ) {`,
  replace: `    (writableFinished || isWritable(stream) === false) &&
    (!wState || wState.pendingcb === undefined || wState.pendingcb === 0)
  ) {`,
});

patches.push(
  {
    // Cottontail compat: legacy eager sources push EOF while data is still
    // buffered, so the EOF 'readable' (read() === null) emission fires with
    // data instead of on an empty queue. Track whether the null 'readable'
    // was delivered and, if not, emit it once right before 'end' for
    // 'readable'-listening consumers.
    file: /internal\/streams\/readable\.js$/,
    find: `  if (!state.destroyed && !state.errored && (state.length || state.ended)) {
    stream.emit('readable')
    state.emittedReadable = false
  }`,
    replace: `  if (!state.destroyed && !state.errored && (state.length || state.ended)) {
    if (state.length === 0 && state.ended) state.ctNullReadableEmitted = true
    stream.emit('readable')
    state.emittedReadable = false
  }`,
  },
  {
    file: /internal\/streams\/readable\.js$/,
    find: `  if (!state.errored && !state.closeEmitted && !state.endEmitted && state.length === 0) {
    state.endEmitted = true
    stream.emit('end')`,
    replace: `  if (!state.errored && !state.closeEmitted && !state.endEmitted && state.length === 0) {
    if (state.ctLegacyEager && state.readableListening && !state.ctNullReadableEmitted && !state.destroyed) {
      state.ctNullReadableEmitted = true
      stream.emit('readable')
      if (state.endEmitted) return
    }
    state.endEmitted = true
    stream.emit('end')`,
  },
);

patches.push({
  // Debug aid: set globalThis.__ct_stream_debug = true to trace stream internals.
  file: /ours\/util\.js$/,
  find: `  debuglog() {
    return function () {}
  },`,
  replace: `  debuglog(name) {
    return function (...args) {
      if (globalThis.__ct_stream_debug) {
        try { console.error('[' + name + ']', ...args) } catch {}
      }
    }
  },`,
});

const shimPlugin = {
  name: "ct-shims",
  setup(build) {
    build.onLoad({ filter: /package\/lib\/.*\.js$/ }, (args) => {
      let contents = fs.readFileSync(args.path, "utf8");
      let touched = false;
      for (const patch of patches) {
        if (patch.file.test(args.path)) {
          if (!contents.includes(patch.find)) throw new Error("patch anchor not found in " + args.path);
          contents = contents.replace(patch.find, patch.replace);
          touched = true;
        }
      }
      return touched ? { contents, loader: "js" } : undefined;
    });
    build.onResolve({ filter: /^(events|buffer|string_decoder\/|process\/|abort-controller)$/ }, (args) => ({
      path: args.path,
      namespace: "ct-shim",
    }));
    build.onLoad({ filter: /.*/, namespace: "ct-shim" }, (args) => ({
      contents: shims[args.path],
      loader: "js",
    }));
    build.onResolve({ filter: /^ct-entry$/ }, () => ({ path: "ct-entry", namespace: "ct-entry" }));
    build.onLoad({ filter: /.*/, namespace: "ct-entry" }, () => ({
      contents: entrySource,
      loader: "js",
      resolveDir: SCRATCH,
    }));
  },
};

const result = await Bun.build({
  entrypoints: ["ct-entry"],
  bundle: true,
  format: "esm",
  keepNames: true,
  minify: {
    identifiers: false,
    syntax: true,
    whitespace: true,
  },
  target: "browser",
  plugins: [shimPlugin],
});
if (!result.success || result.outputs.length !== 1) {
  throw new AggregateError(result.logs, "Failed to bundle readable-stream");
}
fs.writeFileSync(OUT, banner + await result.outputs[0].text());
console.log("built", OUT, fs.statSync(OUT).size, "bytes");
